function params = xarm7_params()
% Parameters for the UFACTORY xArm 7. All numbers from the URDF that
% Vinh shared with the team (xarm_description, autogenerated from xacro).

    params.dof        = 7;
    params.reach_m    = 0.700;
    params.payload_kg = 3.5;
    params.weight_kg  = 13.7;

    % Joint position limits (rad), from URDF
    params.joint_lower = [-3.1101767270538954, -2.18, -3.1101767270538954, ...
                          -0.11, -3.1101767270538954, -1.75, -3.1101767270538954];
    params.joint_upper = [ 3.1101767270538954,  2.18,  3.1101767270538954, ...
                           3.1101767270538954,  3.1101767270538954, ...
                           3.1101767270538954,  3.1101767270538954];

    % URDF gives all velocity limits as 3.14 rad/s
    params.vel_limit = 3.14 * ones(1, 7);

    % Torque limits from URDF: joints 1-2 = 50 Nm, 3-5 = 30 Nm, 6-7 = 20 Nm
    params.effort_limit = [50 50 30 30 30 20 20];

    % Link masses (kg) - base then links 1-7
    params.link_mass = [0.88556 2.382 1.869 1.6383 1.7269 1.3203 1.325 0.17];

    params.local_urdf = fullfile(fileparts(mfilename('fullpath')), '..', ...
                                 'urdf', 'xarm7.urdf');

    % Starting pose - I'll need to tweak these once we test in the lab
    params.q_home  = zeros(1, 7);
    params.q_ready = wrapToPi(deg2rad([0, -45, 0, 70, 0, 115, 0]));
end
